"""
Seed MySQL database with FULL realistic user set
Reads users_to_seed.json generated by generate_realistic_dataset.py
"""

import mysql.connector
import bcrypt
import json
import os
import time

# Database configuration
DB_CONFIG = {
    'host': 'localhost',
    'user': 'root',
    'password': 'password',  # Default for this environment often
    'database': 'apartment_management'
}

def hash_password(password):
    """Hash password using bcrypt"""
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed.decode('utf-8')

def seed_users():
    print("=" * 60)
    print("SEEDING MYSQL - FULL REALISTIC DATASET")
    print("=" * 60)
    
    # 1. Load users from JSON
    json_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'users_to_seed.json')
    
    if not os.path.exists(json_path):
        print(f"❌ Error: {json_path} not found!")
        print("   Run generate_realistic_dataset.py first.")
        return

    try:
        with open(json_path, 'r') as f:
            users = json.load(f)
        print(f"✓ Loaded {len(users)} users from JSON")
    except Exception as e:
        print(f"❌ Error reading JSON: {e}")
        return

    try:
        # 2. Connect to MySQL - Try multiple common passwords
        conn = None
        passwords_to_try = ['password', 'root', '', 'admin', 'password123', 'admin123']
        
        for pwd in passwords_to_try:
            try:
                current_config = DB_CONFIG.copy()
                if pwd == '':
                    del current_config['password']
                else:
                    current_config['password'] = pwd
                    
                print(f"   Attempting connection with password: '{pwd}'...")
                conn = mysql.connector.connect(**current_config)
                if conn.is_connected():
                    print(f"✓ Connected to MySQL with password: '{pwd}'")
                    break
            except mysql.connector.Error:
                continue
                
        if not conn or not conn.is_connected():
            print("\n❌ Could not connect to MySQL with common passwords.")
            print("   Please check your MySQL configuration.")
            return

        cursor = conn.cursor()

        # 3. Clear existing users
        print("Clearing existing users...")
        cursor.execute("DELETE FROM users") # Wipe cleanly to ensure consistency
        conn.commit()
        print("✓ Existing users cleared")

        # 4. Insert users
        print("Inserting new users...")
        insert_query = """
            INSERT INTO users (user_id, username, email, password_hash, role, full_name, 
                             room_no, apartment_name, apartment_no, department, managed_building)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
        
        # Batch insert for performance
        batch_size = 100
        batch_data = []
        
        # Pre-hash generic password to speed up
        generic_hash = hash_password("password123")
        
        for user in users:
            # Add missing fields with None
            user_data = (
                user['user_id'],
                user['username'],
                user['email'],
                generic_hash, # use same hash for speed
                user['role'],
                user['full_name'],
                user.get('room_no'),
                user.get('apartment_name'),
                user.get('apartment_no'), # Often same as room_no for some logic
                user.get('department'),
                user.get('managed_building')
            )
            batch_data.append(user_data)
            
            if len(batch_data) >= batch_size:
                cursor.executemany(insert_query, batch_data)
                conn.commit()
                print(f"   Inserted {len(batch_data)} users...")
                batch_data = []
        
        if batch_data:
            cursor.executemany(insert_query, batch_data)
            conn.commit()
            print(f"   Inserted remaining {len(batch_data)} users...")

        print("\n" + "=" * 60)
        print(f"✅ SUCCESSFULLY SEEDED {len(users)} USERS!")
        print("=" * 60)
        
        cursor.close()
        conn.close()

    except mysql.connector.Error as err:
        print(f"❌ MySQL Error: {err}")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    seed_users()
